services:
  front:
    build: ./front
    mem_limit: 128m
    cpus: 0.25

  back:
    build: ./back
    mem_limit: 256m
    cpus: 0.50

  proxy:
    build: ./web-server
    ports:
      - "8080:80"
    depends_on:
      - front
      - back
    mem_limit: 128m
    cpus: 0.25